Add Pagination + PaginationButton Component
franc5/store pull request #20
Opened 2021-02-12 01:21 UTC by magarciaprieto

Closed #16. Some comments about this issue:
1-href was discarded as a prop. This was decided in an aside meeting.
2- selectedPage (Pagination component prop) is an optional prop with default value = 1.
3- activePage (PaginationButton prop) was not included in Typechecking props. I consider that this prop is design to work internally, it will never have a user interaction. The other reason to do this, was to delete it from Storybook, since it makes no sense to dynamically assign a value to this prop. What do you think about this?
4- Added a target attribute to the anchor tag. The reason, is to make the a:focus styling visible. (yes, it says a:focus, since a:active didn't do what I wanted).
5- The "previous" and "next" buttons were not necessary to include in this component, this was decided in an aside meeting. But I would like to do this, if you approve...  just because I have no idea of how to, and will be a good exercise. Tell me what you think about it.

Hug boss!

2021-02-20 19:06 UTC, franc5 requested changes
I like that you colocated the `PaginationButton` together with the `Pagination`. Colocation it's a good approach to organize a project. I'll pass you a couple of blogpost about this topic later.

Tip: You can also colocate stories of related components, having for example a story for Pagination with bot, the `PaginationButton` and the `Pagination` itself.

2021-02-20 19:06 UTC, franc5 commented on src/components/Pagination/index.js
> +        </PaginationButton>
To make it easy to see where the child component is, instead of adding an extra indentation to it, you can close the parent tag as:

```jsx
<Pagination
  ... propsHere
>
  childrenHere
</Pagination>
```

2021-02-20 19:06 UTC, franc5 commented on src/components/Pagination/index.module.css
> +}
Indentation issue. Use two spaces to indent.

2021-02-25 01:19 UTC, magarciaprieto commented
Closed #20

2021-02-25 23:45 UTC, franc5 requested changes
A few comments to be addressed.

BTW, what was wrong with [this comment](https://github.com/franc5/store/pull/20/files#r579694671).

2021-02-25 23:45 UTC, franc5 commented on src/components/Pagination/PaginationButton/index.js
> +    e.preventDefault();
Good catch!

2021-02-25 23:45 UTC, franc5 commented on src/components/Pagination/index.js
> +              onPageSelected(pageNumber)}}
The indentation used here makes this a little bit difficult to read. At a first glance we have three indentation levels, but both the second one and the third one should be the same. Also, by closing tags, curly-braces, etc, at the same indentation level in which they were opened increase readability.

I'd write this as follows:

```jsx
onClick={pageNumber => {
  if(pageNumber === currentPage) return;
  setCurrentPage(pageNumber); 
  onPageSelected(pageNumber);
}} 
```

2021-02-25 23:45 UTC, franc5 commented on src/components/Pagination/index.stories.js
> +  onPageSelected: pageNumber => console.log(pageNumber)
IIRC, the [Controls addon](https://storybook.js.org/docs/react/essentials/controls)/[Actions addon](https://storybook.js.org/docs/react/essentials/actions) do/does the magic automatically, there's no need to console log anything, right? Also, by letting the addons do their trick, we get the action displayed in the integrated __Actions__ tab, and if the signature of `onPageSelected` changes, we don't need to update anything here.

Thoughts?

2021-02-26 01:12 UTC, magarciaprieto commented on src/components/Pagination/index.stories.js
> +  onPageSelected: pageNumber => console.log(pageNumber)
Totally agree.

2021-02-26 01:34 UTC, magarciaprieto commented on src/components/Pagination/index.js
> +        </PaginationButton>
I have just understand what you were trying to say here haha. I made the change requested.

2021-02-26 01:38 UTC, magarciaprieto commented
All changes requested were addressed. Closed #16 via #20

2021-03-04 14:37 UTC, franc5 approved these changes
PR looks really good! Great job! 🙌

2021-03-04 14:37 UTC, merged