Add Mock API
franc5/store pull request #23
Opened 2021-02-25 02:37 UTC by magarciaprieto

Closed #19 .

In an aside meeting it was determined that the function's name will be changed to getItems() (previously: getFiles() ). The number of items in the array of objects was set to 5. 

Cheers boss!

2021-02-25 03:03 UTC, magarciaprieto commented
Sorry about the milestones in this PR hehe. I forgot to save some changes.

Tschüss!

2021-02-25 23:30 UTC, franc5 commented on src/index.js
> +  < MockApi />
`MockApi` isn't a React component, it's just VanillaJS. Adding this here breaks the app. Let's have a conversation on a side to properly discuss this.

2021-02-25 23:31 UTC, franc5 requested changes
Please, address [this comment](https://github.com/franc5/store/pull/23/files#r583277559).

2021-02-26 01:09 UTC, magarciaprieto commented on src/index.js
> +  < MockApi />
This was written before our last meeting. I'll delete it right now, sorry.

2021-02-26 01:39 UTC, magarciaprieto commented
All changes requested were addressed. Closed #19 via #23

2021-03-04 14:39 UTC, franc5 approved these changes

2021-03-04 14:39 UTC, franc5 commented on src/index.js
> +import MockApi from './api'
We can avoid importing `MockApi` here. Let's delete this line in a separated PR.

2021-03-04 14:39 UTC, merged