Issue24/app interaction
franc5/store pull request #26
Opened 2021-03-17 04:00 UTC by magarciaprieto

Boss, closed #24.

To solve this issue, I made a few changes in another files, such as:
1-  `image: 'https://www.cstatic-images.com/car-pictures/main/usd10chs082d021001.png',` Mistakenly, this was `img` in our last PR and I didn't notice it before, so I renamed it.
2- Added some CSS lines to ItemList Component.
3- Deleted line `import MockApi from './api'` from the index.js file. This was a requested change in the last PR.

Please, do not consider the styles in this issue to be definitive. I used this task, to explore and practice "new concepts" of CSS. 

Kind regards !

XOXO

2021-03-21 18:59 UTC, franc5 requested changes
I left only one comment to be addressed this time, I want you to focus on that particular comment.

BTW, I like the way you're creating atomic commits, it's something that helps when working with git.

2021-03-21 18:59 UTC, franc5 commented on src/api/index.js
> +export {itemsReturned};
If you take a look to the whole file, what we're doing here is:
1. Creating an array with some items (`items`).
2. Creating a function that simply returns that array (`getItems`).
3. Initializing and exporting a variable `itemsReturned` which value is the result of executing `getItems`, ie `items`.

If this were what we want, we can simply export `items`, because in the end, `itemsReturned` has the same item list as `items` does.

This problems was the result of a bad review of #23. The code that solves #19, should be something like:

```javascript
const items = [
  // Populate array here
];

export function getItems() {
  return items:
}
```

With this code, by simply importing `getItems` in a React component, you can execute the function and get the item list.

2021-03-21 22:58 UTC, magarciaprieto commented on src/api/index.js
> +export {itemsReturned};
Boss, after our class two days ago I did exactly this changes, I sent you some pictures about this in Signal. See u! I'll push the new version today.

2021-03-21 23:02 UTC, magarciaprieto commented on src/api/index.js
> +export {itemsReturned};
Done! Closed #24 via #26

2021-03-27 21:43 UTC, franc5 requested changes
PR looks really good! I've just left one extra comment for you to address before merging.

You're also improving the way you commit, trying to create atomic and as much independent as commits, it's great seeing you moving in that direction! 💪

2021-03-27 21:43 UTC, franc5 commented on src/components/Home/index.module.css
> +}
The idea behind CSS Modules is to isolate the styles of a component and prevent affecting the rest of the UI. This is in particular important when a project starts to grow and we have many components out there; If the styles imported by one or more components affects the styles of other parts of the UI, it turns into a difficult situation to manage.

You can move this to [`src/index.css` ](https://github.com/franc5/store/blob/main/src/index.css) file crated for this purpose.

2021-03-28 21:27 UTC, magarciaprieto commented on src/components/Home/index.module.css
> +}
Closed #24 . The solution you gave me was really nice, but eventually I will have to change it again to be presentable hehe.

Hug!

2021-03-30 01:25 UTC, franc5 approved these changes

2021-03-30 01:25 UTC, merged

2021-03-30 01:27 UTC, franc5 commented
Great job @magarciaprieto ! You're learning really fast! 🙌

2021-04-01 20:37 UTC, magarciaprieto commented
> Great job @magarciaprieto ! You're learning really fast! 🙌

You are just sweetening my ear, this is full teamwork. And also, I have the best boss. 

See ya! I'm starting with the newest issues.